class SolarEVIntegrationPanel extends IntegrationEditor {
 constructor(){super();this.shadowRoot.innerHTML='<p style="padding:32px">Loading Solar EV Studio…</p>';}
 set hass(hass){this._hass=hass;if(!this.runtime)this.refresh();else this.live();}
 connectedCallback(){super.connectedCallback();this.timer=setInterval(()=>this.refresh(),5000);}
 disconnectedCallback(){clearInterval(this.timer);}
 async refresh(){if(this.loading||this.busy||!this._hass)return;this.loading=true;try{const state=await this._hass.callWS({type:'solar_ev_studio/get'});this.runtime=state;if(!this.draft){this.config={settings:state.settings};this.draft={...state.settings,factor:state.learned_factor};this.editRevision=state.revision;this.render();}this.live();}catch(e){if(!this.draft)this.shadowRoot.textContent='Unable to load Solar EV Studio: '+(e.message||String(e));else this.say(e.message||String(e),true);}finally{this.loading=false;}}
 live(){if(!this.runtime)return;const root=this.shadowRoot;const status=root.querySelector('#status');if(status)status.textContent=this.runtime.status;const toggle=root.querySelector('#toggle');if(toggle){toggle.textContent=this.runtime.enabled?'Pause solar charging':'Enable solar charging';toggle.disabled=!!this.busy||!!this.runtime.pending_stops.length;}for(const el of root.querySelectorAll('[data-live]')){const s=this._hass.states[this.runtime.settings[el.dataset.live+'_entity']];el.textContent=s?`${s.state} ${s.attributes.unit_of_measurement||''}`:'Unavailable';}}
 render(){super.render();if(!this.draft)return;this.shadowRoot.querySelector('#toggle').onclick=async()=>{if(this.busy)return;this.busy=true;this.live();try{this.runtime=await this._hass.callWS({type:'solar_ev_studio/enable',enabled:!this.runtime.enabled});this.say(this.runtime.status);}catch(e){this.say(e.message||String(e),true);}finally{this.busy=false;this.live();}};
 this.shadowRoot.querySelector('#reset').onclick=async()=>{this.dirty=false;this.draft=null;this.runtime=null;await this.refresh();this.say('Loaded current integration settings.');};}
 async save(){if(this.busy)return;let settings;try{settings=validate(this.draft,this._hass.states);}catch(e){this.say(e.message,true);return;}this.busy=true;for(const el of this.shadowRoot.querySelectorAll('input,select,button'))el.disabled=true;this.say('Stopping charging and saving integration settings…');try{const state=await this._hass.callWS({type:'solar_ev_studio/save',settings,revision:this.editRevision});this.runtime=state;this.config={settings:state.settings};this.draft={...state.settings};this.editRevision=state.revision;this.dirty=false;this.say('Saved in the integration. Charging is paused; enable solar charging to resume.');}catch(e){this.say('Save failed: '+(e.message||String(e))+'. Check controller status and retry.',true);}finally{this.busy=false;for(const el of this.shadowRoot.querySelectorAll('input,select,button'))el.disabled=false;await this.refresh();this.live();}}
}
if(!customElements.get('solar-ev-integration-panel'))customElements.define('solar-ev-integration-panel',SolarEVIntegrationPanel);
