const SOURCES={pv:['Solar production','sensor.totals_pv_power','sensor','W',90],grid:['Grid power','sensor.totals_grid_power','sensor','W',90],battery:['Battery power','sensor.totals_battery_power','sensor','W',90],load:['Total load (including EV)','sensor.totals_load_power','sensor','W',90],voltage:['Supply voltage','sensor.totals_ac_output_voltage','sensor','V',300],soc:['Home battery charge','sensor.totals_battery_state_of_charge','sensor','%',7200],light:['Light intensity','sensor.light_intensity','sensor','Klux',600],ev:['Actual EV power','sensor.ev_charger_phase_a_power','sensor','kW',0],amps:['Actual EV current','sensor.ev_charger_phase_a_current','sensor','A',0],command:['Charging current control','number.ev_charger_charging_current','number','A',0],switch:['Charger switch','switch.ev_charger_switch_2','switch'],work:['Charger work state','sensor.ev_charger_work_state','sensor'],mode:['Charger mode','select.ev_charger_work_mode','select'],sun:['Daylight','sun.sun','sun']};
const FIELDS=[
['cap','Maximum current','Charging',32,6,32,1,'A'],['grid_limit','Grid import tolerance','Charging',500,0,5000,10,'W'],['battery_limit','Battery discharge tolerance','Charging',500,0,5000,10,'W'],['floor','Minimum home battery','Charging',30,0,90,1,'%'],['reserve','Battery charging reserve','Charging',0,0,10000,10,'W'],['margin','Solar headroom','Charging',300,0,5000,10,'W'],
['factor','Light → solar factor','Solar model',20,0.01,100000,0.01,'W / light unit'],['factor_max','Learning factor ceiling','Solar model',40,0.01,100000,0.01,'W / light unit'],['pv_model_max','Estimated PV ceiling','Solar model',15000,100,100000,100,'W'],['min_light','Minimum daylight reading','Solar model',1,0,100000,0.1,'light units'],['start_light','Exploratory start light','Solar model',100,0,100000,1,'light units'],['start_pv','Exploratory start PV','Solar model',1500,0,100000,10,'W'],['probe_pv','Minimum PV for an upward test','Solar model',500,0,100000,10,'W'],['rise_fraction','Required share of current-step power','Solar model',0.5,0.1,1,0.05,'fraction'],['house_tolerance','House-load change tolerance','Solar model',600,0,5000,10,'W'],['solar_tolerance','Solar confirmation tolerance','Solar model',300,0,5000,10,'W'],['reserve_tolerance','Battery charging reserve tolerance','Solar model',200,0,5000,10,'W'],['reserve_release','Release charging reserve at','Solar model',95,0,100,1,'%'],['soc_hysteresis','Battery restart margin','Solar model',5,0,20,1,'%'],
['fast_probe','Test interval when light predicts capacity','Timing',300,60,7200,1,'s'],['slow_probe','Test interval despite unchanged light','Timing',600,60,7200,1,'s'],['cooldown','Restart cooldown','Timing',600,30,7200,1,'s'],['start_dwell','Stable sunlight before start','Timing',120,15,1800,1,'s'],['settle','Wait for charger response','Timing',150,30,900,1,'s'],['feedback_max','Maximum charger feedback age','Timing',240,60,1800,1,'s'],['fresh_after','Ignore feedback this long after command','Timing',30,5,300,1,'s'],['probe_fresh','Maximum feedback age before testing','Timing',150,30,900,1,'s'],['ack_timeout','Current acknowledgement timeout','Timing',30,5,120,1,'s'],['switch_timeout','Switch acknowledgement timeout','Timing',15,5,120,1,'s'],['actuator_delay','Pause after setting current','Timing',5,1,30,1,'s'],['poll','Controller check interval','Timing',15,5,30,1,'s'],['urgent_dwell','Urgent draw trigger dwell','Timing',5,0,30,1,'s'],['urgent_grid','Urgent grid import trigger','Timing',500,0,10000,10,'W'],['urgent_battery','Urgent battery discharge trigger','Timing',500,0,10000,10,'W'],
['idle_power','EV power below which charge is finished','Validation',300,0,1000,10,'W'],['amp_tolerance','Measured current tolerance','Validation',1.5,0.1,5,0.1,'A'],['voltage_min','Minimum supply voltage','Validation',180,80,260,1,'V'],['voltage_max','Maximum supply voltage','Validation',270,100,300,1,'V'],['ev_max','Maximum plausible EV power','Validation',15000,1000,100000,100,'W'],['pv_max','Maximum plausible PV power','Validation',30000,1000,200000,100,'W'],['load_max','Maximum plausible site load','Validation',40000,1000,200000,100,'W']];
const DEFAULTS={levels:'6,8,10,13,16,20,24,32',grid_sign:1,battery_sign:1,mode_state:'charge_now',day_state:'above_horizon',free_state:'charger_free',insert_state:'charger_insert',wait_state:'charger_wait',pause_state:'charger_pause',end_state:'charger_end',charging_state:'charger_charging',fault_state:'charger_fault',free_fault_state:'charger_free_fault'};
for(const [k,, ,v] of FIELDS) DEFAULTS[k]=v;
for(const [k,[,id,,unit,age]] of Object.entries(SOURCES)){DEFAULTS[k+'_entity']=id;if(unit){DEFAULTS[k+'_unit']=unit;DEFAULTS[k+'_age']=age;}}
function validate(input,states){
 const c={...DEFAULTS,...input};
 for(const [k,label,, ,min,max] of FIELDS) if(!Number.isFinite(c[k])||c[k]<min||c[k]>max)throw Error(`${label}: enter ${min}–${max}.`);
 const levels=String(c.levels).split(',').map(x=>Number(x.trim()));
 if(!levels.length||levels.some(x=>!Number.isInteger(x)||x<6||x>32)||new Set(levels).size!==levels.length)throw Error('Supported currents must be unique whole amps from 6 to 32.');
 levels.sort((a,b)=>a-b);if(!levels.includes(c.cap))throw Error('Maximum current must be one of the supported currents.');c.levels=levels.join(',');
 if(c.settle>=c.feedback_max||c.fresh_after>=c.settle||c.ack_timeout>=c.feedback_max)throw Error('Feedback timeout must exceed settling and acknowledgement time; settling must exceed the fresh-feedback delay.');
 if(c.voltage_min>=c.voltage_max||c.factor>c.factor_max||c.floor+c.soc_hysteresis>100||c.slow_probe<c.fast_probe)throw Error('Check voltage range, light factor ceiling, battery recovery margin, and probe intervals.');
 if(![5,6,10,12,15,20,30].includes(c.poll))throw Error('Check interval must be 5, 6, 10, 12, 15, 20 or 30 seconds.');
 for(const k of ['grid_sign','battery_sign'])if(![1,-1].includes(c[k]))throw Error('Power sign must be +1 or −1.');
 for(const [k,[label,,domain,unit]] of Object.entries(SOURCES)){
  const id=c[k+'_entity'];if(typeof id!=='string'||!new RegExp('^'+domain+'\\.[a-z0-9_]+$').test(id))throw Error(`${label}: choose a ${domain} entity.`);
  if(states&&!states[id])throw Error(`${label}: entity does not exist.`);
  if(unit){const u=c[k+'_unit'];const allowed=['pv','grid','battery','load','ev'].includes(k)?['W','kW']:k==='light'?null:[unit];if(typeof u!=='string'||!u.length||u.length>24||/["'\\\r\n]/.test(u)||allowed&&!allowed.includes(u))throw Error(`${label}: invalid units.`);if(!Number.isFinite(c[k+'_age'])||c[k+'_age']<0||c[k+'_age']>86400)throw Error(`${label}: invalid freshness timeout.`);if(states&&states[id].attributes.unit_of_measurement!==u)throw Error(`${label}: expected ${u}, entity reports ${states[id].attributes.unit_of_measurement}.`);}
 }
 for(const k of Object.keys(DEFAULTS).filter(k=>k.endsWith('_state')))if(typeof c[k]!=='string'||! /^[a-zA-Z0-9_ -]{1,60}$/.test(c[k]))throw Error(`Invalid state value: ${k}`);
 return c;
}

const MASTER='input_boolean.solar_ev_charging_enabled', LOCK='input_boolean.solar_ev_configuring';
const AUTO_IDS=['automation.solar_ev_charging_controller','automation.solar_ev_mode_and_restart_interlock','automation.solar_ev_stop_watchdog'];
const HELPER_KEYS={cap:'solar_ev_max_current',floor:'solar_ev_min_battery',reserve:'solar_ev_power_reserve',margin:'solar_ev_margin',factor:'solar_ev_light_factor'};
const esc=x=>String(x??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
class IntegrationEditor extends HTMLElement {
 constructor(){super();this.attachShadow({mode:'open'});}
 setConfig(config){if(this.busy)return;this.config=structuredClone(config);if(!this.dirty){this.draft={...DEFAULTS,...config.settings};this.render();}}
 set hass(hass){const first=!this._hass;this._hass=hass;if(first&&this.draft){for(const [k,id] of Object.entries(HELPER_KEYS)){const n=Number(hass.states['input_number.'+id]?.state);if(Number.isFinite(n))this.draft[k]=n;}this.render();}else if(!this.shadowRoot.querySelector('main'))this.render();this.live();}
 getCardSize(){return 12;}
 connectedCallback(){this.render();}
 live(){if(!this._hass)return;const s=this._hass.states;const status=this.shadowRoot.querySelector('#status');if(status)status.textContent=s['input_text.solar_ev_status']?.state||'Waiting for controller';
  const toggle=this.shadowRoot.querySelector('#toggle');if(toggle){toggle.textContent=s[MASTER]?.state==='on'?'Pause solar charging':'Enable solar charging';toggle.disabled=this.busy||s[LOCK]?.state==='on';}
  for(const el of this.shadowRoot.querySelectorAll('[data-live]')){const id=this.draft?.[el.dataset.live+'_entity'];el.textContent=s[id]?`${s[id].state} ${s[id].attributes.unit_of_measurement||''}`:'Unavailable';}
 }
 render(){if(!this.draft)return;const c=this.draft;
  const field=(k,label,unit='',type='number',min='',max='',step='any')=>`<label>${esc(label)}${unit?` <small>${esc(unit)}</small>`:''}<input data-key="${k}" type="${type}" value="${esc(c[k])}" min="${min}" max="${max}" step="${step}"></label>`;
  this.shadowRoot.innerHTML=`<style>
  :host{display:block;color:var(--primary-text-color,#eaf4f1);font-family:var(--paper-font-body1_-_font-family,system-ui)}*{box-sizing:border-box}main{max-width:1250px;margin:auto;padding:28px;background:var(--primary-background-color,#101e20);border-radius:24px}header{display:flex;justify-content:space-between;align-items:center;gap:20px}h1{font-size:34px;letter-spacing:-1px;margin:5px 0}h2{font-size:19px;margin:0 0 16px}.eyebrow{font-size:11px;letter-spacing:2px;color:#5eaf93;font-weight:750}p{color:var(--secondary-text-color,#a6baba);line-height:1.55;font-size:14px}button{border:1px solid #638d7c66;border-radius:12px;background:var(--card-background-color,#1b3030);color:inherit;padding:13px 20px;font:600 14px system-ui;cursor:pointer}button.primary{background:#bee7bb;color:#143629;border:0}button:disabled{opacity:.45;cursor:wait}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}.metric,section,details{background:var(--card-background-color,#192c2d);border:1px solid #71998b30;border-radius:18px;padding:22px}.metric b{display:block;font-size:23px;margin-top:8px}.metric span,small{color:var(--secondary-text-color,#a6baba);font-size:12px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}label{font-size:13px;display:block;line-height:1.5}input,select{display:block;width:100%;margin-top:7px;padding:12px;border:1px solid #77958a55;border-radius:9px;background:var(--primary-background-color,#101e20);color:inherit;font:14px system-ui}input:focus,select:focus{outline:2px solid #8eccad}.source{padding:18px 0;border-top:1px solid #71998b30}.source .grid{grid-template-columns:2fr 1fr 1fr}.source .entity{grid-column:1/-1}details,section{margin-bottom:16px}summary{font-weight:650;cursor:pointer;margin:0}details[open] summary{margin-bottom:20px}footer{position:sticky;bottom:0;display:flex;align-items:center;gap:12px;flex-wrap:wrap;background:var(--card-background-color,#192c2d);padding:18px;border-radius:15px;border:1px solid #71998b44}#message{flex:1;font-size:13px;min-width:180px;white-space:pre-wrap}.error{color:#ef9b87}.note{border-left:3px solid #96bd7f;padding-left:16px}.badges{display:flex;gap:8px;flex-wrap:wrap;margin:15px 0}.badges span{border-radius:20px;border:1px solid #77958a55;padding:6px 11px;font-size:12px}.stategrid{margin-top:18px}@media(max-width:750px){main{padding:16px}.grid{grid-template-columns:1fr 1fr}.metrics{grid-template-columns:1fr 1fr}header{display:block}header button{margin-top:12px}.source .grid{grid-template-columns:1fr 1fr}h1{font-size:28px}}@media(max-width:450px){.grid{grid-template-columns:1fr}.source .grid{grid-template-columns:1fr}}
  </style><main><header><div><div class="eyebrow">ENERGY / SOLAR EV STUDIO</div><h1>Charge with the sun.</h1><p id="status">Connecting…</p></div><button id="toggle">Enable solar charging</button></header>
  <div class="metrics">${[['pv','Solar production'],['ev','Car power'],['grid','Grid power'],['battery','Battery power']].map(([k,t])=>`<div class="metric"><span>${t}</span><b data-live="${k}">—</b></div>`).join('')}</div>
  <section><h2>Charging preferences</h2><p>Each limit is a separate tolerance. The controller reduces or pauses charging above it; brief draw can occur while measurements and charger commands catch up.</p><div class="grid">${FIELDS.filter(x=>x[2]==='Charging').map(([k,l,, ,min,max,step,u])=>field(k,l,u,'number',min,max,step)).join('')}${field('levels','Supported current steps','comma-separated amps','text')}</div><div class="badges">${String(c.levels).split(',').map(x=>`<span>${esc(x)} A</span>`).join('')}</div></section>
  <details><summary>Entities & measurement units</summary><p>Choose the actual power sensors, including total site load with EV demand. This controller uses a single-phase charger with a switch and a number entity for current.</p>${Object.entries(SOURCES).map(([k,[label,,domain,unit]])=>`<div class="source"><div class="grid"><label class="entity">${esc(label)}<input data-key="${k}_entity" list="entities-${domain}" value="${esc(c[k+'_entity'])}" autocomplete="off"></label>${unit?field(k+'_unit','Expected unit','','text')+field(k+'_age','Maximum reading age','s; 0 = no age check','number',0,86400,1):''}${['grid','battery'].includes(k)?`<label>Positive readings mean<select data-key="${k}_sign"><option value="1" ${c[k+'_sign']===1?'selected':''}>${k==='grid'?'Import':'Battery charging'}</option><option value="-1" ${c[k+'_sign']===-1?'selected':''}>${k==='grid'?'Export':'Battery discharging'}</option></select></label>`:''}</div></div>`).join('')}
  ${[...new Set(Object.values(SOURCES).map(x=>x[2]))].map(d=>`<datalist id="entities-${d}">${Object.entries(this._hass?.states||{}).filter(([id])=>id.startsWith(d+'.')).map(([id,s])=>`<option value="${esc(id)}">${esc(s.attributes.friendly_name||id)}</option>`).join('')}</datalist>`).join('')} <details class="stategrid"><summary>Charger state names</summary><div class="grid">${Object.keys(DEFAULTS).filter(k=>k.endsWith('_state')).map(k=>field(k,k.replaceAll('_',' '),'','text')).join('')}</div></details></details>
  ${['Solar model','Timing','Validation'].map(group=>`<details><summary>${group}</summary><p>${group==='Solar model'?'Light suggests when to test. Measured solar, grid and battery power decide whether a higher current stays. The factor learns upward after confirmed solar charging.':group==='Timing'?'The slower test interval discovers unused solar even if light has not changed. Use response timing that matches your charger’s reporting cadence.':'Invalid units, stale essential readings, and implausible readings prevent charging.'}</p><div class="grid">${FIELDS.filter(x=>x[2]===group).map(([k,l,, ,min,max,step,u])=>field(k,l,u,'number',min,max,step)).join('')}</div></details>`).join('')}
  <p class="note">Settings are saved in the Solar EV Studio integration and continue working with this screen closed. Saving pauses solar charging. After a successful save, use Enable solar charging to resume.</p><footer><span id="message" role="status">${esc(this.message||'All settings saved.')}</span><button id="reset">Discard edits</button><button id="export">Export settings</button><button class="primary" id="save">Save & pause charging</button></footer></main>`;
  for(const el of this.shadowRoot.querySelectorAll('[data-key]'))el.addEventListener('input',()=>{const k=el.dataset.key;this.draft[k]=el.type==='number'||k.endsWith('_sign')?Number(el.value):el.value;this.dirty=true;this.say('Unsaved changes.');});
  this.shadowRoot.querySelector('#save').onclick=()=>this.save();
  this.shadowRoot.querySelector('#reset').onclick=()=>{this.dirty=false;this.draft={...DEFAULTS,...this.config.settings};this.message='Edits discarded.';this.render();};
  this.shadowRoot.querySelector('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(this.draft,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='solar-ev-settings.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  this.shadowRoot.querySelector('#toggle').onclick=async()=>{try{if(this._hass.states[LOCK]?.state==='on')throw Error('Finish saving settings before enabling charging.');await this._hass.callService('input_boolean',this._hass.states[MASTER]?.state==='on'?'turn_off':'turn_on',{entity_id:MASTER});}catch(e){this.say(e.message||String(e),true);}};
  this.live();
 }
 say(message,error=false){this.message=message;const el=this.shadowRoot.querySelector('#message');if(el){el.textContent=message;el.classList.toggle('error',error);}}
}

class SolarEVIntegrationPanel extends IntegrationEditor {
 constructor(){super();this.shadowRoot.innerHTML='<p style="padding:32px">Loading Solar EV Studio…</p>';}
 set hass(hass){this._hass=hass;if(!this.runtime)this.refresh();else this.live();}
 connectedCallback(){super.connectedCallback();this.timer=setInterval(()=>this.refresh(),5000);}
 disconnectedCallback(){clearInterval(this.timer);}
 async refresh(){if(this.loading||this.busy||!this._hass)return;this.loading=true;try{const state=await this._hass.callWS({type:'solar_ev_studio/get'});this.runtime=state;if(!this.draft){this.config={settings:state.settings};this.draft={...state.settings,factor:state.learned_factor};this.editRevision=state.revision;this.render();}this.live();}catch(e){if(!this.draft)this.shadowRoot.textContent='Unable to load Solar EV Studio: '+(e.message||String(e));else this.say(e.message||String(e),true);}finally{this.loading=false;}}
 live(){if(!this.runtime)return;const root=this.shadowRoot;const status=root.querySelector('#status');if(status)status.textContent=this.runtime.status;const toggle=root.querySelector('#toggle');if(toggle){toggle.textContent=this.runtime.enabled?'Pause solar charging':'Enable solar charging';toggle.disabled=!!this.busy||!!this.runtime.pending_stops.length;}for(const el of root.querySelectorAll('[data-live]')){const s=this._hass.states[this.runtime.settings[el.dataset.live+'_entity']];el.textContent=s?`${s.state} ${s.attributes.unit_of_measurement||''}`:'Unavailable';}}
 render(){super.render();if(!this.draft)return;this.shadowRoot.querySelector('#toggle').onclick=async()=>{if(this.busy)return;this.busy=true;this.live();try{this.runtime=await this._hass.callWS({type:'solar_ev_studio/enable',enabled:!this.runtime.enabled});this.say(this.runtime.status);}catch(e){this.say(e.message||String(e),true);}finally{this.busy=false;this.live();}};
 this.shadowRoot.querySelector('#reset').onclick=async()=>{this.dirty=false;this.draft=null;this.runtime=null;await this.refresh();this.say('Loaded current integration settings.');};}
 async save(){if(this.busy)return;let settings;try{settings=validate(this.draft,this._hass.states);}catch(e){this.say(e.message,true);return;}this.busy=true;for(const el of this.shadowRoot.querySelectorAll('input,select,button'))el.disabled=true;this.say('Stopping charging and saving integration settings…');try{const state=await this._hass.callWS({type:'solar_ev_studio/save',settings,revision:this.editRevision});this.runtime=state;this.config={settings:state.settings};this.draft={...state.settings};this.editRevision=state.revision;this.dirty=false;this.say('Saved in the integration. Charging is paused; enable solar charging to resume.');}catch(e){this.say('Save failed: '+(e.message||String(e))+'. Check controller status and retry.',true);}finally{this.busy=false;for(const el of this.shadowRoot.querySelectorAll('input,select,button'))el.disabled=false;await this.refresh();this.live();}}
}
if(!customElements.get('solar-ev-integration-panel'))customElements.define('solar-ev-integration-panel',SolarEVIntegrationPanel);
